module.exports = [
    //column 1
    //Desktop computer
    { selector: '(//a[@class="nav-list-link"])[1]', section: 'COMPUTER SYSTEMS', arrow: 'empty'},
    { selector: '(//a[@class="nav-list-link"])[2]', section: 'DESKTOP COMPUTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[1]'},
    //other
    { selector: '(//a[@class="nav-list-link"])[3]', section: 'GAMING DESKTOPS', arrow: 'empty'},
    { selector: '(//a[@class="nav-list-link"])[4]', section: 'ALL-IN-ONE COMPUTERS', arrow: 'empty'},
    { selector: '(//a[@class="nav-list-link"])[5]', section: 'SERVER & WORKSTATION SYSTEMS', arrow: 'empty'},
    { selector: '(//a[@class="nav-list-link"])[6]', section: 'CHROMEBOX DESKTOPS & MINI PCS', arrow: 'empty'},
    { selector: '(//a[@class="nav-list-link"])[7]', section: 'BUSINESS DESKTOPS', arrow: 'empty'},
    //column 2
    //laptops and notebooks
    { selector: '(//a[@class="nav-list-link"])[8]', section: 'LAPTOPS / NOTEBOOKS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[2]'},
    //2-in-1 laptops
    { selector: '(//a[@class="nav-list-link"])[9]', section: '2-IN-1 LAPTOPS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[3]' },
    { selector: '(//a[@class="nav-list-link"])[10]', section: '2 IN 1 ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[3]' },
    { selector: '(//a[@class="nav-list-link"])[11]', section: 'EXTERNAL CD / DVD / BLU-RAY DRIVES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[3]' },
    //other
    { selector: '(//a[@class="nav-list-link"])[12]', section: 'CHROMEBOOKS', arrow: 'empty' },
    //mobile workstation
    { selector: '(//a[@class="nav-list-link"])[13]', section: 'MOBILE WORKSTATIONS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    { selector: '(//a[@class="nav-list-link"])[14]', section: 'LAPTOP ADD-ON CARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    { selector: '(//a[@class="nav-list-link"])[15]', section: 'LAPTOP BATTERIES / AC ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    { selector: '(//a[@class="nav-list-link"])[16]', section: 'LAPTOP INTERNAL HARD DRIVES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    { selector: '(//a[@class="nav-list-link"])[17]', section: 'LAPTOP MEMORY', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    { selector: '(//a[@class="nav-list-link"])[18]', section: 'LAPTOP NETWORKING', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    { selector: '(//a[@class="nav-list-link"])[19]', section: 'LAPTOP COOLING PADS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    { selector: '(//a[@class="nav-list-link"])[20]', section: 'MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    //other
    { selector: '(//a[@class="nav-list-link"])[21]', section: 'LAPTOPS / NOTEBOOKS', arrow: 'empty' },
    { selector: '(//a[@class="nav-list-link"])[22]', section: 'MICROSOFT SURFACE', arrow: 'empty' },
    //column 3
    //Gaming Laptops
    { selector: '(//a[@class="nav-list-link"])[23]', section: 'GAMING LAPTOPS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[5]' },
    { selector: '(//a[@class="nav-list-link"])[24]', section: 'LAPTOP ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[5]' },
    { selector: '(//a[@class="nav-list-link"])[25]', section: 'GAMING MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[5]' },
    { selector: '(//a[@class="nav-list-link"])[26]', section: 'GAMING KEYBOARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[5]' },
    { selector: '(//a[@class="nav-list-link"])[27]', section: 'MOUSE PADS & ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[5]' },
    //other (even though they are all gaming laptops that aren't in the gaming laptop section for some reason)
    { selector: '(//a[@class="nav-list-link"])[28]', section: 'GAMING LAPTOPS', arrow: 'empty' },
    { selector: '(//a[@class="nav-list-link"])[29]', section: 'GAMING LAPTOPS', arrow: 'empty' },
    { selector: '(//a[@class="nav-list-link"])[30]', section: 'GAMING LAPTOPS', arrow: 'empty' },
    { selector: '(//a[@class="nav-list-link"])[31]', section: 'GAMING LAPTOPS', arrow: 'empty' },
    { selector: '(//a[@class="nav-list-link"])[32]', section: 'GAMING LAPTOPS', arrow: 'empty' },
    //Colume 4
    //33 through 39 are all for the blue links on the side and not the search links
    //So I'll be skipping them
    //Monitors
    { selector: '(//a[@class="nav-list-link"])[40]', section: 'LCD / LED MONITORS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[6]' },
    { selector: '(//a[@class="nav-list-link"])[41]', section: 'GAMING MONITORS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[6]' },
    { selector: '(//a[@class="nav-list-link"])[42]', section: 'TOUCH SCREEN MONITORS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[6]' },
    { selector: '(//a[@class="nav-list-link"])[43]', section: 'MONITOR ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[6]' },
    { selector: '(//a[@class="nav-list-link"])[44]', section: 'MONITORS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[6]' },
    //Input Devices
    { selector: '(//a[@class="nav-list-link"])[45]', section: 'COMPUTER GLASSES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[46]', section: 'GAMING CHAIRS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[47]', section: 'GAMING KEYBOARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[48]', section: 'GAMING MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[49]', section: 'GRAPHICS TABLETS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[50]', section: 'HEADSETS & ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[51]', section: 'KEYBOARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[52]', section: 'MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[53]', section: 'MICROPHONES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[54]', section: 'PC GAME CONTROLLERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[55]', section: 'PRESENTATION REMOTES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[56]', section: 'SOUND CARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[57]', section: 'VR ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[58]', section: 'VR HEADSETS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[59]', section: 'WEB CAMS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[60]', section: 'ADD-ON CARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[61]', section: 'KVM CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[62]', section: 'MOUSE PADS & ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[63]', section: 'SOUND CARD ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    //mice and keyboards
    { selector: '(//a[@class="nav-list-link"])[64]', section: 'KEYBOARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[65]', section: 'GAMING KEYBOARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[66]', section: 'MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[67]', section: 'GAMING MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[68]', section: 'MOUSE / KEYBOARD (PS2) CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[69]', section: 'MOUSE PADS & ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[70]', section: 'OTHER ADAPTERS & GENDER CHANGERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[71]', section: 'STANDARD BATTERIES & CHARGERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    //Printers/scanners
    { selector: '(//a[@class="nav-list-link"])[72]', section: '3D PRINTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[73]', section: 'LASER PRINTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[74]', section: 'INKJET PRINTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[75]', section: 'BARCODE & LABEL PRINTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[76]', section: 'CARD PRINTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[77]', section: 'DOT MATRIX PRINTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[78]', section: 'RECEIPT PRINTER', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[79]', section: '3D SCANNERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[80]', section: 'BARCODE SCANNER', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[81]', section: 'DOCUMENT SCANNERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[82]', section: 'FAX MACHINES & COPIERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[83]', section: 'FLATBED SCANNERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[84]', section: 'SPECIALIZED SCANNERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[85]', section: 'INK CARTRIDGES (AFTERMARKET)', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[86]', section: 'INK CARTRIDGES (GENUINE BRANDS)', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[87]', section: 'LABELS & LABELMAKERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[88]', section: 'PRINTER (PARALLEL) CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[89]', section: 'PRINTER & SCANNER SUPPLIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[90]', section: 'USB CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[91]', section: 'TONER CARTRIDGES (AFTERMARKET)', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[92]', section: 'TONER CARTRIDGES (GENUINE BRANDS)', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    { selector: '(//a[@class="nav-list-link"])[93]', section: 'PRINTER RIBBONS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[9]' },
    //power protection
    { selector: '(//a[@class="nav-list-link"])[94]', section: 'POWER DISTRIBUTION UNIT', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[10]' },
    { selector: '(//a[@class="nav-list-link"])[95]', section: 'POWER INVERTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[10]' },
    { selector: '(//a[@class="nav-list-link"])[96]', section: 'POWER STRIPS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[10]' },
    { selector: '(//a[@class="nav-list-link"])[97]', section: 'SURGE PROTECTORS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[10]' },
    { selector: '(//a[@class="nav-list-link"])[98]', section: 'UPS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[10]' },
    { selector: '(//a[@class="nav-list-link"])[99]', section: 'UPS ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[10]' },
    //headset
    { selector: '(//a[@class="nav-list-link"])[100]', section: 'HEADSETS & ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[11]' },
    { selector: '(//a[@class="nav-list-link"])[101]', section: 'MICROPHONES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[11]' },
    { selector: '(//a[@class="nav-list-link"])[102]', section: 'SOUND CARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[11]' },
    { selector: '(//a[@class="nav-list-link"])[103]', section: 'SPEAKERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[11]' },
    { selector: '(//a[@class="nav-list-link"])[104]', section: 'SOUND CARD ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[11]' },
    //printer ink
    { selector: '(//a[@class="nav-list-link"])[105]', section: 'INK CARTRIDGES (GENUINE BRANDS)', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[12]' },
    { selector: '(//a[@class="nav-list-link"])[106]', section: 'INK CARTRIDGES (AFTERMARKET)', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[12]' },
    { selector: '(//a[@class="nav-list-link"])[107]', section: 'TONER CARTRIDGES (GENUINE BRANDS)', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[12]' },
    { selector: '(//a[@class="nav-list-link"])[108]', section: 'TONER CARTRIDGES (AFTERMARKET)', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[12]' },
    { selector: '(//a[@class="nav-list-link"])[109]', section: 'LABELS & LABELMAKERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[12]' },
    { selector: '(//a[@class="nav-list-link"])[110]', section: 'PRINTER & SCANNER SUPPLIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[12]' },
    { selector: '(//a[@class="nav-list-link"])[111]', section: 'PRINTER RIBBONS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[12]' },
    //no dropout
    { selector: '(//a[@class="nav-list-link"])[112]', section: 'KVM SWITCHES', arrow: 'empty' },
    // projectors

    { selector: '(//a[@class="nav-list-link"])[113]', section: 'HOME THEATER PROJECTORS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[13]' },
    { selector: '(//a[@class="nav-list-link"])[114]', section: 'BUSINESS PROJECTORS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[13]' },
    { selector: '(//a[@class="nav-list-link"])[115]', section: 'PROJECTOR ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[13]' },
    { selector: '(//a[@class="nav-list-link"])[116]', section: 'PROJECTOR LAMPS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[13]' },
    { selector: '(//a[@class="nav-list-link"])[117]', section: 'PROJECTOR SCREENS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[13]' },
    //3d Printing
    
    { selector: '(//a[@class="nav-list-link"])[118]', section: '3D PRINTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[14]' },
    { selector: '(//a[@class="nav-list-link"])[119]', section: '3D SCANNERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[14]' },
    { selector: '(//a[@class="nav-list-link"])[120]', section: 'FILAMENT', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[14]' },
    { selector: '(//a[@class="nav-list-link"])[121]', section: '3D PRINTERS ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[14]' },
    //Computer Accessories
    { selector: '(//a[@class="nav-list-link"])[122]', section: 'ADD-ON CARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[123]', section: 'CABLE MANAGEMENT', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[124]', section: 'CARD READERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[125]', section: 'CASE ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[126]', section: 'CASE FANS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[127]', section: 'COMPUTER GLASSES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[128]', section: 'CONTROLLER PANELS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[129]', section: 'CPU ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[130]', section: 'CPU FANS & HEATSINKS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[131]', section: 'DIY COOLING', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[132]', section: 'HARD DRIVE COOLING', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[133]', section: 'HARD DRIVE ENCLOSURES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[134]', section: 'LAPTOP ADD-ON CARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[135]', section: 'LAPTOP NETWORKING', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[136]', section: 'MEMORY & CHIPSET COOLING', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[137]', section: 'OTHER COMPUTER ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[138]', section: 'PC TOOLS & TESTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[139]', section: 'SSD / HDD ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[140]', section: 'THERMAL COMPOUND / GREASE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[141]', section: 'USB CHARGERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[142]', section: 'USB GADGETS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[143]', section: 'VGA COOLING', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[144]', section: 'WATER / LIQUID COOLING', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    { selector: '(//a[@class="nav-list-link"])[145]', section: 'WIRED ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[15]' },
    //Laptop Accessories
    { selector: '(//a[@class="nav-list-link"])[146]', section: 'LAPTOP INTERNAL HARD DRIVES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[16]' },
    { selector: '(//a[@class="nav-list-link"])[147]', section: 'LAPTOP ADD-ON CARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[16]' },
    { selector: '(//a[@class="nav-list-link"])[148]', section: 'LAPTOP BATTERIES / AC ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[16]' },
    { selector: '(//a[@class="nav-list-link"])[149]', section: 'LAPTOP COOLING PADS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[16]' },
    { selector: '(//a[@class="nav-list-link"])[150]', section: 'LAPTOP MEMORY', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[16]' },
    { selector: '(//a[@class="nav-list-link"])[151]', section: 'LAPTOP NETWORKING', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[16]' },
    { selector: '(//a[@class="nav-list-link"])[152]', section: 'SECURITY LOCKS & ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[16]' },
    { selector: '(//a[@class="nav-list-link"])[153]', section: 'MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[16]' },
    //no dropout arrow
    { selector: '(//a[@class="nav-list-link"])[154]', section: 'LAPTOP CASES & BAGS', arrow: 'empty' },
    { selector: '(//a[@class="nav-list-link"])[155]', section: 'DOCKING STATIONS', arrow: 'empty' },
    //cables
    { selector: '(//a[@class="nav-list-link"])[156]', section: 'LIGHTNING CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[157]', section: 'USB CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[158]', section: 'DISPLAYPORT CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[159]', section: 'HDMI CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[160]', section: 'MINI DISPLAYPORT CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[161]', section: 'THUNDERBOLT CABLES & ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[162]', section: 'VGA / SVGA CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[163]', section: '3.5MM / 2.5MM STEREO CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[164]', section: 'INSTRUMENT (PROFESSIONAL) CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]'  },
    { selector: '(//a[@class="nav-list-link"])[165]', section: 'RCA CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]'  },
    { selector: '(//a[@class="nav-list-link"])[166]', section: 'RCA COMPONENT CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[167]', section: 'RCA COMPOSITE CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[168]', section: 'S-VIDEO CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[169]', section: 'SPEAKER WIRES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[170]', section: 'TOSLINK DIGITAL OPTICAL AUDIO CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[171]', section: 'SCSI / SAS / INFINIBAND CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[172]', section: 'AC POWER CORDS FOR LAPTOP', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[173]', section: 'COMPUTER POWER ADAPTER CORDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[174]', section: 'COMPUTER POWER CORDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[175]', section: 'COMPUTER POWER EXTENSION CORDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[176]', section: 'INTERNATIONAL POWER CORDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[177]', section: 'POWER EXTENSION CORDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[178]', section: 'POWER SPLITTER CORDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    { selector: '(//a[@class="nav-list-link"])[179]', section: 'DVI CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[17]' },
    //no dropout arrow
    { selector: '(//a[@class="nav-list-link"])[180]', section: 'HUBS', arrow: 'empty' },
    //adapters and gendered connectors
    { selector: '(//a[@class="nav-list-link"])[181]', section: 'AUDIO ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[182]', section: 'AUDIO VIDEO CONVERTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[183]', section: 'AUDIO/VIDEO SPLITTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[184]', section: 'AUDIO/VIDEO SWITCH', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[185]', section: 'CONNECTORS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[186]', section: 'DATA ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[187]', section: 'DATA CONVERTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[188]', section: 'EXTENDERS & REPEATERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[189]', section: 'HARD DRIVE ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[190]', section: 'MODULAR ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[191]', section: 'MOUSE/KEYBOARD (PS2) ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[192]', section: 'NETWORK CONNECTORS/ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[193]', section: 'POWER ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[194]', section: 'USB / IEEE-1394 FIREWIRE ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[195]', section: 'USB CONVERTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[196]', section: 'USB DISPLAY ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[197]', section: 'VIDEO ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    { selector: '(//a[@class="nav-list-link"])[198]', section: 'OTHER ADAPTERS & GENDER CHANGERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[18]' },
    //Refurbished, no dropout arrow
    { selector: '(//a[@class="nav-list-link"])[199]', section: 'DESKTOP COMPUTERS', arrow: 'empty' },
    { selector: '(//a[@class="nav-list-link"])[200]', section: 'LAPTOPS / NOTEBOOKS', arrow: 'empty' },
    { selector: '(//a[@class="nav-list-link"])[201]', section: 'GAMING LAPTOPS', arrow: 'empty' },
    { selector: '(//a[@class="nav-list-link"])[202]', section: '2-IN-1 LAPTOPS', arrow: 'empty' },
    { selector: '(//a[@class="nav-list-link"])[203]', section: 'CHROMEBOOKS', arrow: 'empty' },
    { selector: '(//a[@class="nav-list-link"])[204]', section: 'INPUT DEVICES', arrow: 'empty' },
    { selector: '(//a[@class="nav-list-link"])[205]', section: 'APPLE', arrow: 'empty' },

]