module.exports = [
    //default computer system button
    { selector: '(//a[@class="nav-list-link"])[1]', section: 'COMPUTER SYSTEMS', arrow: 'empty'},
    { selector: '(//a[@class="nav-list-link"])[2]', section: 'DESKTOP COMPUTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[1]'},
    { selector: '(//a[@class="nav-list-link"])[3]', section: 'LAPTOPS / NOTEBOOKS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[2]'},
    //2 in 1 laptop and children
    { selector: '(//a[@class="nav-list-link"])[4]', section: '2-IN-1 LAPTOPS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[3]'},
    { selector: '(//a[@class="nav-list-link"])[5]', section: '2 IN 1 ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[3]'},
    { selector: '(//a[@class="nav-list-link"])[6]', section: 'EXTERNAL CD / DVD / BLU-RAY DRIVES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[3]'},
    //mobile workstations and children
    { selector: '(//a[@class="nav-list-link"])[7]', section: 'MOBILE WORKSTATIONS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]'},
    { selector: '(//a[@class="nav-list-link"])[8]', section: 'LAPTOP ADD-ON CARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]'},
    { selector: '(//a[@class="nav-list-link"])[9]', section: 'LAPTOP BATTERIES / AC ADAPTERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    { selector: '(//a[@class="nav-list-link"])[10]', section: 'LAPTOP INTERNAL HARD DRIVES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    { selector: '(//a[@class="nav-list-link"])[11]', section: 'LAPTOP MEMORY', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    { selector: '(//a[@class="nav-list-link"])[12]', section: 'LAPTOP NETWORKING', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    { selector: '(//a[@class="nav-list-link"])[13]', section: 'LAPTOP COOLING PADS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    { selector: '(//a[@class="nav-list-link"])[14]', section: 'MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[4]' },
    //Gaming laptops section and children
    { selector: '(//a[@class="nav-list-link"])[15]', section: 'GAMING LAPTOPS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[5]' },
    { selector: '(//a[@class="nav-list-link"])[16]', section: 'LAPTOP ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[5]' },
    { selector: '(//a[@class="nav-list-link"])[17]', section: 'GAMING MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[5]' },
    { selector: '(//a[@class="nav-list-link"])[18]', section: 'GAMING KEYBOARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[5]' },
    { selector: '(//a[@class="nav-list-link"])[19]', section: 'MOUSE PADS & ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[5]' },
    //Monitors and Children
    { selector: '(//a[@class="nav-list-link"])[20]', section: 'LCD / LED MONITORS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[6]' },
    { selector: '(//a[@class="nav-list-link"])[21]', section: 'GAMING MONITORS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[6]' },
    { selector: '(//a[@class="nav-list-link"])[22]', section: 'TOUCH SCREEN MONITORS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[6]' },
    { selector: '(//a[@class="nav-list-link"])[23]', section: 'MONITOR ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[6]' },
    { selector: '(//a[@class="nav-list-link"])[24]', section: 'MONITORS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[6]' },
    //Input Devices and children
    { selector: '(//a[@class="nav-list-link"])[25]', section: 'COMPUTER GLASSES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[26]', section: 'GAMING CHAIRS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[27]', section: 'GAMING KEYBOARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[28]', section: 'GAMING MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[29]', section: 'GRAPHICS TABLETS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[30]', section: 'HEADSETS & ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[31]', section: 'KEYBOARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[32]', section: 'MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[33]', section: 'MICROPHONES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[34]', section: 'PC GAME CONTROLLERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[35]', section: 'PRESENTATION REMOTES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[36]', section: 'SOUND CARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[37]', section: 'VR ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[38]', section: 'VR HEADSETS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[39]', section: 'WEB CAMS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[40]', section: 'ADD-ON CARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[41]', section: 'KVM CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[42]', section: 'MOUSE PADS & ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]' },
    { selector: '(//a[@class="nav-list-link"])[43]', section: 'SOUND CARD ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[7]'},
    //keyboard and mouse section
    { selector: '(//a[@class="nav-list-link"])[44]', section: 'KEYBOARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[45]', section: 'GAMING KEYBOARDS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[46]', section: 'MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[47]', section: 'GAMING MICE', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[48]', section: 'MOUSE / KEYBOARD (PS2) CABLES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[49]', section: 'MOUSE PADS & ACCESSORIES', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[50]', section: 'OTHER ADAPTERS & GENDER CHANGERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
    { selector: '(//a[@class="nav-list-link"])[51]', section: 'STANDARD BATTERIES & CHARGERS', arrow: '(//a[@class="nav-list-link menu-box-trigger"])[8]' },
]